# Generated by Django 4.1.4 on 2022-12-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='references',
            name='Photo',
            field=models.ImageField(default='staticÉ872633_630546525429055_6007909932726738695_n.jpg', max_length=200, upload_to='PortfolioBuilderApp\\static'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Photo',
            field=models.ImageField(default='staticÉ872633_630546525429055_6007909932726738695_n.jpg', max_length=200, upload_to='PortfolioBuilderApp\\static'),
        ),
    ]
